[package]
name = "brk_rolldown_plugin_isolated_declaration"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
publish = true
repository.workspace = true
description = "Rolldown plugin for TypeScript isolated declarations"
exclude = ["tests"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
doctest = false

[lints]
workspace = true

[dependencies]
arcstr = { workspace = true }
oxc = { workspace = true }
rolldown_common = { workspace = true }
rolldown_error = { workspace = true }
rolldown_plugin = { workspace = true }
sugar_path = { workspace = true }

[dev-dependencies]
# rolldown_testing = { workspace = true }
testing_macros = { workspace = true }
